#!/bin/bash
#
# Copyright (c) 2014 David Vossel <dvossel@redhat.com>
#					All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
#######################################################################

# Command line option processing

trap job_finished SIGUSR1

CMD_DIR="/var/run/docker_cts_jobs"

job_finished()
{
	if ! [ -f "${CMD_DIR}/${pid}.rc" ]; then
		return
	fi

	rc=$(cat ${CMD_DIR}/${pid}.rc)
	if [ -f "${CMD_DIR}/${pid}.stdout" ]; then
		timeout 2 cat ${CMD_DIR}/${pid}.stdout
	fi

	if [ -f "${CMD_DIR}/$$.stderr" ]; then
		timeout 2 cat ${CMD_DIR}/${pid}.stderr 1>&2
	fi

	rm -rf "${CMD_DIR}/${pid}.stdout" > /dev/null 2>&1
	rm -rf "${CMD_DIR}/${pid}.stderr" > /dev/null 2>&1
	rm -rf "${CMD_DIR}/${pid}.rc" > /dev/null 2>&1

	rm -f "${CMD_DIR}/NODE${pid}" > /dev/null 2>&1
	rm -f "${CMD_DIR}/ARGS${pid}" > /dev/null 2>&1
	rm -f "${CMD_DIR}/JOB${pid}" > /dev/null 2>&1
	exit $rc
}

pid=$$
rm -rf "${CMD_DIR}/${pid}.stdout" > /dev/null 2>&1
rm -rf "${CMD_DIR}/${pid}.stderr" > /dev/null 2>&1
rm -rf "${CMD_DIR}/${pid}.rc" > /dev/null 2>&1

echo "$1" > ${CMD_DIR}/NODE${pid}
shift;
echo "$@" > ${CMD_DIR}/ARGS${pid}
echo "$pid" > ${CMD_DIR}/JOB${pid}

while read line; do
	 : nothing
done

