#!/bin/bash
#
# Copyright (c) 2014 David Vossel <dvossel@redhat.com>
#					All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
#######################################################################

# Command line option processing

pid=$$
rm -rf "/var/run/${pid}.docker_remote.stdout" > /dev/null 2>&1
rm -rf "/var/run/${pid}.docker_remote.stderr" > /dev/null 2>&1
rm -rf "/var/run/${pid}.docker_remote.rc" > /dev/null 2>&1

echo "$pid" > /var/run/docker_remote_daemon_JOB${pid}

while true ; do
	if [ -f "/var/run/${pid}.docker_remote.rc" ]; then
		break
	fi
	usleep 100000
done

rc=$(cat /var/run/${pid}.docker_remote.rc)
if [ -f "/var/run/${pid}.docker_remote.stdout" ]; then
	timeout 2 cat /var/run/${pid}.docker_remote.stdout
fi

if [ -f "/var/run/$$.docker_remote.stderr" ]; then
	timeout 2 cat /var/run/${pid}.docker_remote.stderr 1>&2
fi

rm -rf "/var/run/${pid}.docker_remote.stdout" > /dev/null 2>&1
rm -rf "/var/run/${pid}.docker_remote.stderr" > /dev/null 2>&1
rm -rf "/var/run/${pid}.docker_remote.rc" > /dev/null 2>&1

exit $rc
