#!/bin/bash
#
# Copyright (c) 2014 David Vossel <dvossel@redhat.com>
#					All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
#######################################################################

# Command line option processing

trap job_finished SIGUSR1

job_finished()
{
	if ! [ -f "/var/run/docker_cts_jobs/${pid}.docker_remote.rc" ]; then
		return
	fi

	rc=$(cat /var/run/docker_cts_jobs/${pid}.docker_remote.rc)
	if [ -f "/var/run/docker_cts_jobs/${pid}.docker_remote.stdout" ]; then
		timeout 2 cat /var/run/docker_cts_jobs/${pid}.docker_remote.stdout
	fi

	if [ -f "/var/run/docker_cts_jobs/$$.docker_remote.stderr" ]; then
		timeout 2 cat /var/run/docker_cts_jobs/${pid}.docker_remote.stderr 1>&2
	fi

	rm -rf "/var/run/docker_cts_jobs/${pid}.docker_remote.stdout" > /dev/null 2>&1
	rm -rf "/var/run/docker_cts_jobs/${pid}.docker_remote.stderr" > /dev/null 2>&1
	rm -rf "/var/run/docker_cts_jobs/${pid}.docker_remote.rc" > /dev/null 2>&1

	rm -f "/var/run/docker_cts_jobs/docker_remote_NODE${pid}" > /dev/null 2>&1
	rm -f "/var/run/docker_cts_jobs/docker_remote_ARGS${pid}" > /dev/null 2>&1
	rm -f "/var/run/docker_cts_jobs/docker_remote_JOB${pid}" > /dev/null 2>&1
	exit $rc
}

pid=$$
rm -rf "/var/run/docker_cts_jobs/${pid}.docker_remote.stdout" > /dev/null 2>&1
rm -rf "/var/run/docker_cts_jobs/${pid}.docker_remote.stderr" > /dev/null 2>&1
rm -rf "/var/run/docker_cts_jobs/${pid}.docker_remote.rc" > /dev/null 2>&1

echo "$1" > /var/run/docker_cts_jobs/docker_remote_NODE${pid}
shift;
echo "$@" > /var/run/docker_cts_jobs/docker_remote_ARGS${pid}
echo "$pid" > /var/run/docker_cts_jobs/docker_remote_JOB${pid}

while read line; do
	 : nothing
done

